[project]
name = "utility-manager"
version = "0.1.0"
description = "A unified service to execute different Custom Utility Services via CLI."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer>=0.27.1",
]

[dependency-groups]
dev = [
    "auto-py-to-exe>=2.50.1",
    "pyrefly>=1.2.0",
]
