[project]
name = "utility-manager"
version = "0.1.0"
description = "A unified service to execute different Custom Utility Services via CLI."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer>=0.27.1",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.0",
    "pyrefly>=1.2.0",
]
